### ISSUE TITLE
Path of Exile crashes on boot

### ISSUE THREAD

**Issue by jeromegn** [felixdoerre/primus_vk#29]
Not sure if this is a primus_vk issue or something else, but it works fine on my Intel GPU.

I used `PROTON_LOG=1 ENABLED_PRIMUS_LAYER=1 optirun %command%` to run Path of Exile using Steam Play's Proton 3.16-8 beta (same thing happened with 3.16-7 beta)

Logs from proton: https://gist.github.com/jeromegn/db9c910dc222d9c7c8dbd936458f726d

Do tell if you I should be posting this somewhere else or getting logs from some other source!

**Comment by felixdoerre** [comment]
I don't see any primus_vk related output in the log. Does `primus_vk` work in general? (i.e. with `vulkan-smoketest` or with `vkcube`) From the command you posted, the environment-vaiable is wrong, it's `ENABLE_PRIMUS_LAYER=1` not `ENABLED`.

**Comment by jeromegn** [comment]
I think I had the right environment variable, might have not pasted it right here. I tried this multiple times.

primus_vk does seem to work in general. I tried vkbench with it. It was incredibly slow but it worked.

I don't know if this is an issue with primus_vk specifically, thought it might though. I've been trying to run the game on Lutris instead with the DXVK standalone version and now logs show some Primus VK stuff.

https://gist.github.com/jeromegn/5fb25eef842299e091baf48b45eead7b

**Comment by felixdoerre** [comment]
that log looks better! It also shows a problem, that I understood just a few minutes ago and already fixed in master (so can you please give it another try?). Not getting any `PrimusVK`-prefixed message in the log (like in the output form Steam) makes me still wonder if primus_vk is starting at all.

To "Edit 2": It is expected that the game will not run with `ENABLE_PRIMUS_LAYER=1` without optirun or primusrun, as the layer requires the second graphics card and will fail to initialize properly without it.

**Comment by jeromegn** [comment]
This fixes it! Thanks a lot. Not sure why Proton was eating these logs, it works with Steam and Proton now (and Lutris.)
